soundcloud:
  - https://soundcloud.com/elephantvoices   # scientist-curated calls

youtube_playlists: []  # disabled to avoid sign-in/rate-limit

vimeo_showcases:
  - https://vimeo.com/showcase/theelephantethogram  # annotated ethogram clips
