soundcloud:
  - https://soundcloud.com/elephantvoices   # Ethogram-labeled call examples (scientist curated)

youtube_playlists:
  - https://www.youtube.com/@savetheelephantskenya/videos  # Save the Elephants channel (expert org)

vimeo_showcases:
  - https://vimeo.com/showcase/theelephantethogram          # ElephantVoices Ethogram showcase (annotated)

